# -*- coding: utf-8 -*-
"""Basic_image_processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YTGBN4GQ55AMRgpp17exnooEeN3LUAlu
"""
import numpy as np

def get_margins(arr, th):
  values, counts = np.unique(arr,return_counts= True)
  filtered_values = [values[i] for i in range(len(values)) if counts[i] > th ]
  if filtered_values:
    return np.amin(filtered_values),np.amax(filtered_values)
  return np.amin(arr),np.amax(arr)

"""Each frame has borders with ticks and gray background.
This function finds the crops the relevant parts of the image"""
def crop_image(img):
  n_rows = img.shape[0]
  n_cols = img.shape[1]
  r_th = int(n_rows/5)
  c_th = int(n_cols/5)
  zero_indices = np.where(img == 0)
  row_margins = get_margins(zero_indices[0],r_th)
  col_margins = get_margins(zero_indices[1],c_th)
  return img[row_margins[0]:row_margins[1],col_margins[0]:col_margins[1]]


def center_image(img, square = False):
  n_rows = img.shape[0]
  n_cols = img.shape[1]
  max_dim = max(n_rows,n_cols)
  if square:
    padded_img = np.zeros(( max_dim*2,max_dim*2))
    row_offset = max_dim
    col_offset = int(max_dim / 2)
  else:
    padded_img = np.zeros((n_rows*2,n_cols*2))
    row_offset = n_rows
    col_offset = int(n_cols/2)
  padded_img[row_offset:row_offset+n_rows,col_offset:col_offset+n_cols] = img
  return padded_img







def preprocess_image(img):
  return center_image(crop_image(img),True)

